name: Server Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: yarn install |
      working-directory: ./
      run: yarn install
    - name: Start build
      run: |
        mkdir -p ./dist/assets/atomic-package/dist/js/
        mkdir ./dist/app
        mkdir ./dist/docs
        mkdir ./dist/docs/app
        cp index.html package.json ./dist/
        cp -r images css font ./dist/
        cp -r assets/highlightjs assets/uikit assets/uikit.min.js ./dist/assets/
        cp assets/atomic-package/dist/js/atomic-package.min.js ./dist/assets/atomic-package/dist/js/atomic-package.min.js
        cp -r app/main.min.js ./dist/app/
        cp -r docs/pages docs/images ./dist/docs/
        cp -r docs/index.html ./dist/docs/
        cp -r docs/app/main.min.js ./dist/docs/app/
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        public-key: ${{ secrets.SSH_PUBLIC_KEY }}
    - name: deploy to server
      run: rsync -rlptgoD --delete --exclude ".git/" -e "ssh -i ./id_rsa -o StrictHostKeyChecking=no -p ${SSH_PORT}" dist/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
